using Test
using Base64
using ATProto
using ATProto.Crypto

include(joinpath(@__DIR__, "fixtures", "reference_fixtures.jl"))

_url(s) = replace(replace(s, '+' => '-'), '/' => '_')
# FIXTURES: generated by the multiformats/@noble JS stack (the same libraries
# the TypeScript reference depends on) — see ROADMAP M2 notes.

@testset "varint" begin
    @test varint_encode(UInt64(0)) == [0x00]
    @test varint_encode(UInt64(1)) == [0x01]
    @test varint_encode(UInt64(127)) == [0x7f]
    @test varint_encode(UInt64(128)) == [0x80, 0x01]
    @test varint_encode(UInt64(0x1200)) == [0x80, 0x24]   # multikey multicodec
    @test varint_encode(UInt64(0xe7)) == [0xe7, 0x01]      # secp256k1-pub
    @test varint_encode(UInt64(0x71)) == [0x71]            # dag-cbor
    for u in (UInt64(0), UInt64(1), UInt64(0x71), UInt64(0xe7), UInt64(0x1200),
              UInt64(123456789), typemax(UInt64) >> 8)
        @test varint_decode(varint_encode(u)) == u
    end
    @test varint_decode([0x80, 0x24]) == UInt64(0x1200)
    @test_throws ArgumentError varint_decode([0x80])            # truncated
    @test_throws ArgumentError varint_decode([0x01, 0x02])      # trailing bytes
    @test_throws ArgumentError varint_encode(-1)
    # decode with position
    bytes = [0x80, 0x24, 0xff]
    (v, next) = read_varint(bytes; pos = 1)
    @test v == UInt64(0x1200) && next == 3
end

@testset "base codecs (reference vectors)" begin
    for v in FIXTURES.multibase
        bytes = isempty(v.hex) ? UInt8[] : hex2bytes(v.hex)
        @test multibase_to_bytes(v.encoded) == bytes
    end
    # round-trip every sample through every encoder
    samples = unique(v.hex for v in FIXTURES.multibase)
    for h in samples
        bytes = isempty(h) ? UInt8[] : hex2bytes(h)
        for enc in (:base16, :base16upper, :base32, :base32upper, :base58btc,
                    :base64, :base64pad, :base64url, :base64urlpad)
            @test multibase_to_bytes(bytes_to_multibase(bytes; encoding = enc)) == bytes
        end
    end
end

@testset "base codecs (unit vectors)" begin
    # vectors cross-checked against multiformats JS reference in fixtures;
    # spot checks here with widely known values
    @test base16_encode(hex2bytes("deadbeef")) == "deadbeef"
    @test base16upper_encode(hex2bytes("deadbeef")) == "DEADBEEF"
    @test base16_decode("deadbeef") == hex2bytes("deadbeef")
    @test base16_decode("DEADBEEF") == hex2bytes("deadbeef")

    # RFC 4648 test vectors (base32, unpadded)
    @test base32_encode(codeunits("foobar")) == "mzxw6ytboi"
    @test base32_encode(codeunits("foob")) == "mzxw6yq"
    @test base32_encode(codeunits("fooba")) == "mzxw6ytb"
    @test base32_decode("mzxw6ytboi") == Vector{UInt8}(codeunits("foobar"))
    @test base32upper_encode(codeunits("foobar")) == "MZXW6YTBOI"
    @test base32_decode("MZXW6YTBOI") == Vector{UInt8}(codeunits("foobar"))
    @test_throws ArgumentError base32_decode("m1xw")  # invalid char

    # base58btc: known vectors from Bitcoin/multiformats test suites
    @test base58btc_encode(Vector{UInt8}()) == ""
    @test base58btc_decode("") == UInt8[]
    @test base58btc_encode([0x00]) == "1"
    @test base58btc_decode("1") == [0x00]
    @test base58btc_encode([0x00, 0x00, 0x01]) == "112"
    @test base58btc_decode("112") == [0x00, 0x00, 0x01]
    # sha256("") multihash -> famous CIDv0 prefix "Qm..."
    @test base58btc_decode("QmbWqxBEKC3P8tqsKc98xmWNzrzDtRLMiMPL8wBuTGsMnR") |>
          (b -> (length(b) == 34 && b[1] == 0x12 && b[2] == 0x20))
    @test_throws ArgumentError base58btc_decode("0OIl")  # invalid chars

    # base64 variants (6 bytes = multiple of 3, so no padding is needed at all)
    bytes = hex2bytes("00deadbeef01")
    @test base64_encode(bytes) == "AN6tvu8B"
    @test base64pad_encode(bytes) == "AN6tvu8B"
    @test base64url_encode(bytes) == "AN6tvu8B"
    @test base64urlpad_encode(bytes) == "AN6tvu8B"
    @test base64_decode("AN6tvu8B") == bytes
    @test base64pad_decode("AN6tvu8B") == bytes
    @test base64url_decode("AN6tvu8B") == bytes
    @test base64urlpad_decode("AN6tvu8B") == bytes
    # '+' and '/' in the standard alphabet become '-' and '_' in url-safe
    b64std = Base64.base64encode(hex2bytes("fbffbf"))
    @test base64urlpad_encode(hex2bytes("fbffbf")) == _url(b64std)
end


@testset "multibase" begin
    bytes = hex2bytes("deadbeef01")
    for (enc, prefix) in ((:base16, 'f'), (:base16upper, 'F'), (:base32, 'b'),
                          (:base32upper, 'B'), (:base58btc, 'z'), (:base64, 'm'),
                          (:base64pad, 'M'), (:base64url, 'u'), (:base64urlpad, 'U'))
        mb = bytes_to_multibase(bytes; encoding = enc)
        @test first(mb) == prefix
        @test multibase_to_bytes(mb) == bytes
    end
    @test_throws InvalidMultibaseError multibase_to_bytes("")
    @test_throws InvalidMultibaseError multibase_to_bytes("qabcd")  # unsupported prefix
    @test_throws InvalidMultibaseError bytes_to_multibase(bytes; encoding = :base2)
end

@testset "digests" begin
    @test sha256("") |> (d -> length(d) == 32)
    @test sha256hex("") == "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
    @test sha256hex("abc") == "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad"
    @test sha256_multihash("") ==
          vcat(UInt8(0x12), UInt8(0x20), hex2bytes("e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"))
    @test identity_multihash("hi") == UInt8[0x00, 0x02, 0x68, 0x69]
    @test length(random_bytes(32)) == 32
    @test random_bytes(16) != random_bytes(16)
end
